Feature/#171 friend suggestion
capstone-kw-jjiggle/gitbal-be pull request #173
Opened 2024-08-18 07:17 UTC by leesj000603

## #️⃣연관된 이슈
#171 
> ex) #이슈번호, #이슈번호

## 📝작업 내용
가장 높은 등급에 있는 사람 중 한 명
나랑 같은 언어를 쓰는 사람 중 한 명
나보다 한 등급 높은 사람 중 한 명
나랑 비슷한 점수 범위 중 한 명

위 기준으로 추천 친구 리스트를 제공하도록
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 코드 실행시 - 스크린샷(필수 x, jira 대체 가능)
![image](https://github.com/user-attachments/assets/01b7864c-0ed0-4ead-9efb-34f19d0575f1)
## 💬리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 리팩토링 바로 진행하겠습니다!
> ex) 어떻게 코드를 더 개선할 수 있을까? 이름 추천 등등..

2024-08-19 14:26 UTC, khyojun requested changes
작업 하신다고 고생하셨습니다! 리뷰 남겼으니까 확인하고 수정 후에 한 번 더 언급해주세요!

2024-08-19 14:26 UTC, khyojun commented on src/main/java/gitbal/backend/api/userPage/RandomUserPicker.java
> +public class RandomUserPicker {
오 객체 분리하신거 좋았습니다!
필드를 사용하더라도 불변하게 사용하셔서 유지를 하셨군요! 너무 좋습니다!

2024-08-19 14:26 UTC, khyojun commented on src/main/java/gitbal/backend/api/userPage/UserCalculator.java
> +public class UserCalculator {
객체 분리해주신거 너무 좋습니다! 그렇지만 이 친구는 userPage라는 패키지에 있기 보다는 userDomain과 연결시키면 어떨까 하네요! repository가 있으니까요! 이건 한 번 생각해보시면 좋을 거 같아요!

2024-08-19 14:26 UTC, khyojun commented on src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
> +    User purpleUser = randomUserPicker.getRandomHigestGradeUser(allUsers);
요기 메서드 줄일 수 있을 거 같은데 가능할까요? ㅎㅎ 할 수 있으실 거 같아요! 승준씨라면..!

2024-08-19 14:26 UTC, khyojun commented on src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageUpdater.java
> +//    private void updateWhenSameSize(int oldSize) {
주석 관련해서는 없애셔도 될 거 같아요!

2024-08-19 14:26 UTC, khyojun commented on src/main/java/gitbal/backend/domain/user/User.java
> +    private MajorLanguageJpaEntity majorLanguage = null;
null을 부여해야하는 이유가 있었을까요?

2024-08-19 14:26 UTC, khyojun commented on src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
> +//    @Test
여기 주석도 사실 없애도 될 거 같습니다! 왜냐하면 사실 이제는 사용하지 않을 메서드니까요!

2024-08-20 00:03 UTC, leesj000603 commented on src/main/java/gitbal/backend/domain/user/User.java
> +    private MajorLanguageJpaEntity majorLanguage = null;
MajorLanguage는 user가 회원가입 할 시에 user가 입력하는 값이 아니라, github 에서 graphql를 통해 가져오는 정보기 때문에 바로 객체를 생성하여 메모리를 할당하는 것 보다는 

지금 사용하고 있는 지연 로딩 방식에 맞게 필요할 경우 객체를 메모리에 할당 하고자 하였습니다.

2024-08-20 01:26 UTC, khyojun commented on src/main/java/gitbal/backend/domain/user/User.java
> +    private MajorLanguageJpaEntity majorLanguage = null;
넵! 의도는 좋은 거 같습니다!
그렇지만 null을 선언하지 않아도! 아마 기본적으로 초기값으로 null 값이 들어가는 것으로 알고 있는데요! 명시적으로 선언하여서 확인하기 위한 의도가 있으셨을까요?

출처 : https://kephilab.tistory.com/46

2024-08-20 06:15 UTC, leesj000603 commented on src/main/java/gitbal/backend/domain/user/User.java
> +    private MajorLanguageJpaEntity majorLanguage = null;
@OneToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
@JoinColumn(name = "major_user_id")
private MajorLanguageJPAEntity majorLanguage;
이런 방식을 말씀해주신거군요 그렇군요 따로 명시적으로 선언한 게 확인하려는 의도를 생각하고  했던 건 아니었습니다.

2024-08-20 07:10 UTC, leesj000603 commented on src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
> +//    @Test
넵!

2024-08-20 07:10 UTC, leesj000603 commented on src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageUpdater.java
> +//    private void updateWhenSameSize(int oldSize) {
넵!

2024-08-20 07:10 UTC, leesj000603 commented on src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
> +    User purpleUser = randomUserPicker.getRandomHigestGradeUser(allUsers);
넵 회의 전 까지 진행해보겠습니다!

2024-08-20 07:10 UTC, leesj000603 commented on src/main/java/gitbal/backend/api/userPage/UserCalculator.java
> +public class UserCalculator {
넵 회의 전 까지 진행해보겠습니다!

2024-08-20 07:12 UTC, leesj000603 commented on src/main/java/gitbal/backend/domain/user/User.java
> +    private MajorLanguageJpaEntity majorLanguage = null;
저는 말씀하신 따로 명시적인 null 주입 없이 하는 코드가 더 깔끔하다는 생각이 드는 것 같습니다!

2024-08-20 08:30 UTC, khyojun commented
다시 달아주신것 확인했구요! 수정 다 하시고 한 번 더 불러주시면 제가 확인하고 머지할게요!
일단 이 기회를 틈타..! 제 도메인 오류를 발견해주셔서 감삼니다..! ㅎㅎ 밥이라도 사야겠네요~!

2024-08-21 02:41 UTC, leesj000603 commented
말씀해주신 사항 반영 했습니다!

2024-08-21 03:01 UTC, khyojun commented
conflict 가 발생하네요..! 이건 조금 있다가 시간나는 사람이 해결하고 바로 머지하면 좋겠네요!

2024-08-21 12:29 UTC, khyojun approved these changes

2024-08-21 12:29 UTC, merged